$ErrorActionPreference = 'Continue'
$u8 = New-Object System.Text.UTF8Encoding($false)
$repo = $args[0]
$pp = Join-Path $repo 'v3\src\Dsht.Cli\Program.cs'
$tc = Join-Path $repo 'v3\src\Dsht.Platform.Windows\WindowsToolchainQuery.cs'
$ip = Join-Path $repo 'v3\tools\installer.cs'

function FixAll($path, $a, $b, $label) {
    $enc = New-Object System.Text.UTF8Encoding($false)
    $raw = [System.IO.File]::ReadAllText($path, $enc)
    $crlf = $raw.Contains("`r`n")
    $t = $raw.Replace("`r`n", "`n")
    $n = ([regex]::Matches($t, [regex]::Escape($a))).Count
    if ($n -ge 1) {
        $t = $t.Replace($a, $b.Replace("`r`n", "`n"))
        if ($crlf) { $t = $t.Replace("`n", "`r`n") }
        [System.IO.File]::WriteAllText($path, $t, $enc)
        Write-Host ("  OK   " + $label + " (" + $n + ")")
    } else {
        Write-Host ("  MISS " + $label)
    }
}

Write-Host "=== N1 MAJOR: my autostart verification checks a filename that is never written ==="
FixAll $pp 'dsh-minato.cmd");' 'dsh-minato-autostart.cmd");   // N1 FIX: the write path uses -autostart; the check used the bare name, so it always failed' 'N1 autostart name'

Write-Host "=== N2 MAJOR: the npm registry value carries CRLF, so my regex rejects every real registry ==="
FixAll $tc '            if (!string.IsNullOrEmpty(registry) &&' '            // N2 FIX (CLI audit MAJOR): the captured value ends with CRLF, and the pattern cannot' + "`n" +
    '            // match it - so every real registry was rejected and install/update always failed.' + "`n" +
    '            registry = (registry ?? "").Trim();' + "`n" +
    '            if (!string.IsNullOrEmpty(registry) &&' 'N2 trim registry'

Write-Host "=== N3 MAJOR: the whitelist still allows the cmd.exe metacharacters ==="
FixAll $tc 'System.Text.RegularExpressions.Regex.IsMatch(registry, @"^https?://[A-Za-z0-9._~:/?#\[\]@!$&''()*+,;=%-]+$")' 'System.Text.RegularExpressions.Regex.IsMatch(registry, @"^https?://[A-Za-z0-9._~:/?#\[\]@!$*+,;=-]+$")   // N3 FIX: & % ^ ! ( ) are cmd.exe metacharacters' 'N3 reject metachars'

Write-Host "=== N4 MAJOR: my one-sided window accepts a FUTURE time ==="
FixAll $pp 'double ctDiff = (DateTime.Now - ctParsed).TotalSeconds;' 'double ctDiff = (DateTime.Now - ctParsed).TotalSeconds;   // N4 FIX: a FUTURE time makes this negative' 'N4 comment'
FixAll $pp 'if (ctDiff > 120)' 'if (ctDiff > 120 || ctDiff < -5)   // N4 FIX: negative = future; allow only a tiny clock skew' 'N4 future reject'

Write-Host "=== N5 MAJOR: DataRoot already IS the .dsh directory ==="
FixAll $pp 'string profiles = System.IO.Path.Combine(dshHome, ".dsh", "profiles");' 'string profiles = System.IO.Path.Combine(dshHome, "profiles");   // N5 FIX: DataRoot is already the .dsh dir; the extra segment made the list always empty' 'N5 no double dsh'

Write-Host "=== N7 MINOR: the profile-name regex accepts . and .. ==="
FixAll $pp '!System.Text.RegularExpressions.Regex.IsMatch(profile, @"^[A-Za-z0-9._-]+$")' '(!System.Text.RegularExpressions.Regex.IsMatch(profile, @"^[A-Za-z0-9._-]+$") || profile == "." || profile == "..")   // N7 FIX: dots alone escaped the profiles dir' 'N7 reject dots'

Write-Host "=== plugin uninstall: plugin/ is generated by the installer, not in the manifest ==="
FixAll $ip 'foreach (string gen in new string[] { "uninstall.exe", ".dsh-minato-install", "hashes.txt" })' 'foreach (string gen in new string[] { "uninstall.exe", ".dsh-minato-install", "hashes.txt" })' 'plugin probe'

Write-Host "=== done ==="
