<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Dsht.Contracts.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Dsht.Domain\Dsht.Domain.csproj" />
    <ProjectReference Include="..\..\src\Dsht.Platform.Windows\Dsht.Platform.Windows.csproj" />
    <ProjectReference Include="..\..\src\Dsht.Platform.Linux\Dsht.Platform.Linux.csproj" />
  </ItemGroup>
</Project>